### ISSUE TITLE
Question: Multiple projects with native playwright and BDD

### ISSUE THREAD

**Issue by helmutchecker** [vitalets/playwright-bdd#166]
We have an existing set off native playwright tests running and are looking to evaluate an additional BDD integration. I installed dependencies and ran first BDD test case which works fine, but I am unable to configure the BDD next to our existing playwright tests.

Is there a possibility to configure BDD to be used additional? As after generation basically native playwright with the runner is executed, I was hoping to get this running. I was trying something the following way:

```
  /* Configure projects for existing test suite and BDD */
  projects: [
    {
      name: "BDD Tests",
      testDir: defineBddConfig({
        importTestFrom: "./custom-test.ts",
        paths: ["test-features/**/*.feature"],
        outputDir: "./test-features-generated",
        steps: ["test-features-steps/**/*.ts"],
      }),
    },
    {
      name: "Existing Suite",
      testDir: "./tests",
    },
  ],
```
Edit:
The plugin correctly detects both configs and finds all tests, but when executing non-bdd test, following errors comes up:
```
Error: BDD config not found for testDir: "g:\......\tests". Available testDirs:
g:\......\test-features-generated
```

When trying to define bddconfig also for second project, error is during run:
```
Error: Can't find testMeta for key ""
```

**Comment by vitalets** [comment]
Yes, it should work. Could you share how do you run `but when executing non-bdd test`?

**Comment by helmutchecker** [comment]
I am executing just a regular test like the following:
```typescript
test("Simple test without any dependency @GetStartedSimple", async ({ loggingService }) => {
  loggingService.logMessage("test is being executed ...");
});
```
I execute this directly via Playwright Extension, or directly from command line using `npx playwright test --grep "@GetStartedSimple"`, which is both failing with similar error.

For both projects, I am using the same `custom-test.ts` file with my custom fixtures which is importing `import { test as base } from "playwright-bdd";`. When I change this line back to use default test from playwright, the test runs, but in that case the bdd project will not be working anymore.
During execution, global setup runs, test starts, but fails immediately:

```
Running 1 test using 1 worker
[Existing Suite] › tests\getStartedTest.spec.ts:3:5 › Simple test without any dependency @GetStartedSimple
Error: BDD config not found for testDir: "D:\test-project-bdd\tests". Available testDirs:
D:\test-project-bdd\test-features-generated
  1) [SIT] › tests\getStartedTest.spec.ts:3:5 › Simple test without any dependency @GetStartedSimple

    Error: worker process exited unexpectedly (code=1, signal=null)
```

**Comment by vitalets** [comment]
I get the problem, good catch! Will hotfix it.

**Comment by vitalets** [comment]
Released as **v6.6.0**.
@helmutchecker could you re-check on your side?

**Comment by helmutchecker** [comment]
Retest was working, test executed successfully for both projects. Ticket can be closed.
Thank you for quick investigation and fix.

**Comment by vitalets** [comment]
Thanks for reporting and feedback!

**Comment by kishkk84** [comment]
@helmutchecker @vitalets I am seeing this error any idea how to resolve it?

base.fixture.ts
```
import { mergeTests } from "@playwright/test";
import { test as baseTest } from "./base-test.fixture.ts";
import { test as page } from "./page.fixture.ts";
import { test as bdd, createBdd } from "playwright-bdd";

export const test = mergeTests(baseTest, page, bdd);
export const expect = test.expect;
export const { Given, When, Then } = createBdd(test);
```

Error
```npm run test:e2e                                               

> @project/testing@1.0.0 test:e2e
> test_env=local NODE_OPTIONS="--loader=ts-node/esm --experimental-specifier-resolution=node --no-warnings" npx bddgen && npx playwright test -c playwright.config.ts

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at tests/integration/main-navigation.spec.tsx:3

  1 | import { test, expect } from "../../fixtures/base.fixture.ts";
  2 |
> 3 | test(
    | ^
  4 |   "Login into Merlin",
  5 |   { tag: ["@chrome", "@firefox"] },
  6 |   async ({ mainNavigationComponent, receptionPage }) => {

    at TestTypeImpl._currentSuite (/Users/kisj/Projects/mer/node_modules/@playwright/test/node_modules/playwright/lib/common/testType.js:71:13)
    at TestTypeImpl._createTest (/Users/kisj/Projects/mer/node_modules/@playwright/test/node_modules/playwright/lib/common/testType.js:80:24)
    at test (/Users/kisj/Projects/mer/node_modules/@playwright/test/node_modules/playwright/lib/transform/transform.js:256:12)
    at /Users/kisj/Projects/merpackages/testing/tests/integration/main-navigation.spec.tsx:3:1
```


```
projects: [
    {
      name: "Integration Tests",
      testDir: "./tests/integration",
      //testMatch: /.*.spec.tsx/,
    },
    {
      name: "e2e BDD Tests",
      //testMatch: [/.*.step.tsx/, /.*.spec.js/],
      testDir: defineBddConfig({
        paths: ["./tests/e2e/features/"],
        importTestFrom: "./fixtures/base.fixture",
        require: ["./tests/e2e/steps/*.tsx"],
      }),
    },
    {
      name: "setup",
      testMatch: /.*\.setup\.tsx/,
    },
    {
      name: "chromium",
      grep: [/@all/, /@chrome/],
      use: {
        ...devices["Desktop Chrome"],
        deviceScaleFactor: undefined,
        viewport: null,
        storageState: path.join(
          __dirname,
          "./authentication/storageState.json",
        ),
      },
      dependencies: ["setup"],
    },]
```
