### ISSUE TITLE
Bug: issue with Custom Parameter Types during migration to 7.0.0-0

### ISSUE THREAD

**Issue by alescinskis** [vitalets/playwright-bdd#175]
Hello,

I'm trying to migrate from 6.5.2 to 7.0.0-0 and unable to launch the tests due to custom parameter not being defined.
```json
"devDependencies": {
    "@playwright/test": "1.45.1",
    "playwright-bdd": "7.0.0-0",
```

I've updated the pw config to use `steps` and `features`:  

```typescript   
const testDir = defineBddConfig({
  features: ['tests/e2e', 'tests/visual-regression'],
  steps: ['tests/steps/**/*.ts', 'tests/commonUtils/**/*.ts'],
  outputDir: 'tests/bddgen/',
  featuresRoot: 'tests/',
});
```

I'm defining parameters in `automation/tests/steps/types.ts`:
```typescript
import { defineParameterType } from 'playwright-bdd';
...

type ChangeDirection = 'increased' | 'decreased';

defineParameterType({
  name: 'changeDirection',
  regexp: /increased|decreased/,
  transformer: (s: string) => s.toLowerCase() as ChangeDirection,
});
```
and have a steps `automation/tests/steps/balanceSteps.ts` file:
```typescript
Then(
  'framework verifies that balance {changeDirection}',
  async ({ page, sharedData, viewPortState }, changeDirection: 'increased' | 'decreased'): Promise<void> => {
    const previousBalance = parseFloat(<string>sharedData.balance);
    if (viewPortState.isMobile) {
      const gameFooter = new GameFooter(page);
      await gameFooter.isBalanceChanged(previousBalance, changeDirection);
    } else {
      const wingItem = new WingItem(page);
      await wingItem.isBalanceChanged(previousBalance, changeDirection);
    }
  }
);
```
when I'm trying to launch tests, it throws me such error:
```node
> npx bddgen --tags='@storybook and (not @localisation)' && npx playwright test --workers=3 --quiet

/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/dist/cjs/src/CucumberExpressionError.js:21
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^

Error: This Cucumber Expression has a problem at column 33:

framework verifies that balance {changeDirection}
                                ^---------------^
Undefined parameter type 'changeDirection'.
Please register a ParameterType for 'changeDirection'
    at UndefinedParameterTypeError.CucumberExpressionError [as constructor] (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/dist/cjs/src/CucumberExpressionError.js:21:42)
    at new UndefinedParameterTypeError (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/Errors.ts:218:10)
    at createUndefinedParameterType (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/Errors.ts:227:10)
    at CucumberExpression.rewriteParameter (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:97:41)
    at CucumberExpression.rewriteToRegex (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:50:21)
    at /Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:108:57
    at Array.map (<anonymous>)
    at CucumberExpression.rewriteExpression (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:108:38)
    at CucumberExpression.rewriteToRegex (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:52:21)
    at new CucumberExpression (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/@cucumber/cucumber-expressions/src/CucumberExpression.ts:35:26)
    at registerStepDefinition (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/steps/registry.ts:37:9)
    at Then (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/steps/playwrightStyle.ts:22:27)
    at Object.<anonymous> (/Users/arturslescinskis/GIT/pp-experiment/automation/tests/steps/balanceSteps.ts:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.f._compile (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.i.<computed>.ut._extensions.<computed> (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.requireOrImport (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright/lib/transform/transform.js:192:20)
    at requireOrImport (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/playwright/requireOrImport.ts:11:20)
    at loadSteps (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/steps/load.ts:13:17)
    at TestFilesGenerator.loadSteps (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/gen/index.ts:76:5)
    at async Promise.all (index 1)
    at /Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/gen/index.ts:32:7
    at withExitHandler (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/utils/exit.ts:30:12)
    at TestFilesGenerator.generate (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/gen/index.ts:31:5)
    at async Promise.all (index 0)
    at Command.<anonymous> (/Users/arturslescinskis/GIT/pp-experiment/automation/node_modules/playwright-bdd/src/cli/commands/test.ts:32:5) {
  undefinedParameterTypeName: 'changeDirection'
}

Node.js v20.9.0
```

any references to `@cucumber/cucumber` was replaced by `playwright-bdd` according to [migration guide](https://vitalets.github.io/playwright-bdd/#/guides/migration-v7?id=custom-parameter-types), and node modules were removed, npm cache cleared.

**Comment by vitalets** [comment]
Hey @alescinskis 
Is `automation/tests/steps.types.ts` covered by `steps: ['tests/steps/**/*.ts', 'tests/commonUtils/**/*.ts']`?
Maybe add console.log there to check is it executed?

**Comment by alescinskis** [comment]
the types are actually located `automation/tests/steps/types.ts`, it was a mistake by me.

when I change to `steps: ['automation/tests/**/*.ts'],` it throws `No step definitions found!`. 
with `steps: ['tests/**/*.ts'],` it throws the initial error `Undefined parameter type 'changeDirection'....`

**Comment by vitalets** [comment]
Found a bug: all custom parameters should be loaded before parsing steps. I've updated RC package - 7.0.0-1.
Could you re-install (`npm i -D playwright-bdd@next`) and re-check on your side?
Thank you!

**Comment by alescinskis** [comment]
it did help! thank you very much!
