### ISSUE TITLE
Question: Error while cucumber report generation post test execution

### ISSUE THREAD

**Issue by gitToSantosh** [vitalets/playwright-bdd#250]
I often get below error post test case(s) execution, while generation of cucumber report. The json report file also remains empty.

```
Error in reporter Error: Pickle not found
    at TestCase.findPickle (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCase.ts:133:24)
    at TestCase.addRun (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCase.ts:52:27)
    at C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:123:16
    at Array.forEach (<anonymous>)
    at MessagesBuilder.createTestCases (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:114:23)
    at MessagesBuilder.doBuildMessages (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:91:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CucumberReporterAdapter.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\index.ts:69:5)  
    at ReporterV2Wrapper.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\reporterV2.js:91:12)
    at wrapAsync (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\multiplexer.js:79:12)
    at Multiplexer.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\multiplexer.js:51:25)
    at InternalReporter.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\internalReporter.js:70:12)
    at Runner.runAllTests (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\runner\runner.js:77:28)
    at runTests (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\program.js:218:18)
    at t.<anonymous> (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\program.js:55:7)


Error in reporter Error: Pickle not found
    at TestCase.findPickle (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCase.ts:133:24)
    at TestCase.addRun (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCase.ts:52:27)
    at C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:123:16
    at Array.forEach (<anonymous>)
    at MessagesBuilder.createTestCases (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:114:23)
    at MessagesBuilder.doBuildMessages (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\index.ts:91:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CucumberReporterAdapter.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright-bdd\src\reporter\cucumber\index.ts:69:5)  
    at ReporterV2Wrapper.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\reporterV2.js:91:12)
    at wrapAsync (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\multiplexer.js:79:12)
    at Multiplexer.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\multiplexer.js:51:25)
    at InternalReporter.onEnd (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\reporters\internalReporter.js:70:12)
    at Runner.runAllTests (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\runner\runner.js:77:28)
    at runTests (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\program.js:218:18)
    at t.<anonymous> (C:\Users\ADMIN\Desktop\sample-automation\node_modules\playwright\lib\program.js:55:7)
```

**Comment by vitalets** [comment]
I will definitely enrich error message with more details.
In upcoming playwright-bdd v8 this part was changed, so the error should gone.
Is that error appears on every test run or it's a floating one?

**Comment by gitToSantosh** [comment]
I think I am still using 7.5.0. It does not appear on every test though. But often when I run multiple tests I see this, have no idea why it happens

**Comment by vitalets** [comment]
> I think I am still using 7.5.0. 

Yes, v8 is not released yet.

> It does not appear on every test though.

Could you show the content of your playwright.config.ts (if possible)?

**Comment by gitToSantosh** [comment]
When will the v8 get released ?? 

Also , any idea why we see the other error posted above ??  
**Error in reporter Error: Attachment without body and url**

**Comment by vitalets** [comment]
> When will the v8 get released ??

Within this or next week.

> Also , any idea why we see the other error posted above ??
Error in reporter Error: Attachment without body and url

Do you add any attachments manually in tests?

**Comment by gitToSantosh** [comment]
Nope, even when I commented out the attachments, I still see the error twice , no idea why

**Comment by gitToSantosh** [comment]
I think I am able to reproduce the error now .

I have jar file which i run in a child process. It takes an argument and return a string. Every time this piece of code runs, I get the error "Error in reporter Error: Attachment without body and url"

```
Then( 'I see in title {string}', async ( { page }, pageTitle: string ) => {
	// Verify the page title
	await expect( page ).toHaveTitle( pageTitle );

	try {
		// Run the child process command
		const output = execSync( 'java -jar library.jar "XXXX XXXX XXXX XXXX"' ).toString();

		// Log the output or perform further actions
		console.log( 'Java Help Output:', output );
	} catch ( error ) {
		// Handle potential errors
		console.error( 'Error running command:', error.message );
	}
} );
```

Also even When you run a simple command like "java -help" in a child process, you can see stderr attachment in playwright html report

![image](https://github.com/user-attachments/assets/66c634b6-cec7-4f07-805d-7ad31472bae6)

**Comment by vitalets** [comment]
Fixed in Playwright-BDD v8.
