### ISSUE TITLE
Question:Playwright Test did not expect test() to be called here.

### ISSUE THREAD

**Issue by tutanjamon2020** [vitalets/playwright-bdd#257]
Since I updated my Playwright project to use AWS secret credentials I cannot run the test cases correctly.

I have this error message:

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
 when one of the dependencies in your package.json depends on @playwright/test.

 at example.spec.ts:26

 24 |
 25 | // Test for login functionality, navigation, and work orders check
> 26 | test('Vytal WO View', async ({ page }) => {
 | ^
 27 | test.setTimeout(180_000);
 28 | await login(page);
 29 | await page.click('div.MuiListItemIcon-root.css-1f8bwsm');
 at TestTypeImpl._currentSuite (C:\WINDOWS\system32\node_modules\playwright\lib\common\testType.js:72:13)
 at TestTypeImpl._createTest (C:\WINDOWS\system32\node_modules\playwright\lib\common\testType.js:78:24)
 at C:\WINDOWS\system32\node_modules\playwright\lib\transform\transform.js:288:12
 at Object.<anonymous> (C:\WINDOWS\system32\tests\example.spec.ts:26:5)

I've checked the package.json, playwright.config, helper, etc. files and I can't find any conflicts. Any ideas?

**Comment by vitalets** [comment]
What is the location of you project on your machine? 
By the paths in the error, it looks like some global installation of Playwright is used: 
```
C:\WINDOWS\system32\node_modules\playwright\lib\transform\transform.js
```
I'd expect it something like:
```
C:\WINDOWS\Users\<user>\Projects\<project-name>\node_modules\playwright\...
```

**Comment by vitalets** [comment]
Closing due to inactivity.

**Comment by danieljonsson90** [comment]
For me the issue was that I also used vitest in my app for testing and in vite.config.ts I had to add this and then my playwright tests worked in github actions.

 exclude: [
      ...configDefaults.exclude,
      'tests/**', // ✅ ignore folder
      'tests-examples/**', // ✅ ignore folder
    ],
